spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${TF_DB_USERNAME:talentflow}
    password: ${TF_DB_PASSWORD:}
    url: ${TF_DB_URL:jdbc:mysql://localhost:3306/talentflow_hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
  rabbitmq:
    username: ${TF_RABBITMQ_USERNAME:guest}
    password: ${TF_RABBITMQ_PASSWORD:}
    host: ${TF_RABBITMQ_HOST:127.0.0.1}
    port: ${TF_RABBITMQ_PORT:5672}
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: ${TF_REDIS_HOST:127.0.0.1}
    database: ${TF_REDIS_DATABASE:0}
    port: ${TF_REDIS_PORT:6379}
    password: ${TF_REDIS_PASSWORD:}
  cache:
    cache-names: menus_cache
server:
  port: ${TF_SERVER_PORT:8081}
  compression:
    enabled: true
fastdfs:
  nginx:
    host: ${TF_STORAGE_PUBLIC_BASE_URL:http://127.0.0.1:8081/}
